version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'webservice'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root_bsc'
      MYSQL_ROOT_PASSWORD: 'root_bsc'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: